[package]
name = "xlabs-api"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.5"
rocket = "0.4.10"
clokwerk = "0.3.5"
serde = "1.0.137"
serde_json = "1.0.81"